### ISSUE TITLE
Creating desktop and startmenu shortcuts doesn't work on Windows 7 32/64 bit

### ISSUE THREAD

**Issue by towlie** [notsecure/utox-update#11]
@mohamedkomalo 
The log doesn't show anything about it.

**Comment by towlie** [comment]
Creating shortcuts worked before your pull request.

**Comment by towlie** [comment]
https://github.com/notsecure/utox-update/commit/347bf677b2d2faf32d0a11fd816979a3945662be

**Comment by mohamedkomalo** [comment]
sorry my bad, didn't test them
