### ISSUE TITLE
uTox updater fails unclearly

### ISSUE THREAD

**Issue by TheLastProject** [notsecure/utox-update#5]
Today, a friend tried to install uTox for Windows in C:\Program Files(x86)\Tox\. uTox failed without giving an error message, leaving us confused for a good 10 minutes.

uTox should probably try to install somewhere by default without asking the user unless they want to specifically use another location. Aside from that, uTox should give a clear error message in case of failure, as opposed to only giving a message on success.

**Comment by towlie** [comment]
@TheLastProject I think you can close this since https://github.com/notsecure/utox-update/commit/d7b99394b6e967fbca8beca23da9781be6d7aa3b. It now tells you if you cannot write into that directory and it has a default install location.
